"""settlement jobs events

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 15:57:56.700354
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buildings",
        sa.Column("character_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("damaged", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_buildings_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("character_id", "type", name=op.f("pk_buildings")),
    )
    op.create_table(
        "character_skills",
        sa.Column("character_id", sa.BigInteger(), nullable=False),
        sa.Column("skill", sa.String(length=32), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_character_skills_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("character_id", "skill", name=op.f("pk_character_skills")),
    )
    op.create_table(
        "resources",
        sa.Column("character_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("amount_milli", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_resources_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("character_id", "name", name=op.f("pk_resources")),
    )
    op.create_table(
        "scheduled_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("character_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_scheduled_events_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_events")),
    )
    op.create_index(
        op.f("ix_scheduled_events_character_id"), "scheduled_events", ["character_id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_events_due_at"), "scheduled_events", ["due_at"], unique=False
    )
    op.create_table(
        "activities",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("character_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("ref", sa.String(length=64), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finishes_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_activities_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["scheduled_events.id"],
            name=op.f("fk_activities_event_id_scheduled_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_index(
        op.f("ix_activities_character_id"), "activities", ["character_id"], unique=False
    )
    op.create_table(
        "build_queue",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("character_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("target_level", sa.Integer(), nullable=False),
        sa.Column("cost", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finishes_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_build_queue_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["scheduled_events.id"],
            name=op.f("fk_build_queue_event_id_scheduled_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_build_queue")),
    )
    op.create_index(
        op.f("ix_build_queue_character_id"), "build_queue", ["character_id"], unique=False
    )
    # ### end Alembic commands ###

    # Characters created before M1 get the start resources (docs/03-siedlung.md, "Startzustand")
    op.execute(
        """
        INSERT INTO resources (character_id, name, amount_milli, updated_at)
        SELECT c.id, r.name, r.amount * 1000, now()
        FROM characters c
        CROSS JOIN (VALUES ('wood', 200), ('iron', 50)) AS r(name, amount)
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_build_queue_character_id"), table_name="build_queue")
    op.drop_table("build_queue")
    op.drop_index(op.f("ix_activities_character_id"), table_name="activities")
    op.drop_table("activities")
    op.drop_index(op.f("ix_scheduled_events_due_at"), table_name="scheduled_events")
    op.drop_index(op.f("ix_scheduled_events_character_id"), table_name="scheduled_events")
    op.drop_table("scheduled_events")
    op.drop_table("resources")
    op.drop_table("character_skills")
    op.drop_table("buildings")
    # ### end Alembic commands ###
