"""reputation quests items

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-29 16:21:51.327308
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_flags",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("character_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_character_flags_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_flags")),
    )
    op.create_index(
        op.f("ix_character_flags_character_id"), "character_flags", ["character_id"], unique=False
    )
    op.create_table(
        "items",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("character_id", sa.BigInteger(), nullable=False),
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("equipped", sa.Boolean(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_items_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
    )
    op.create_index(op.f("ix_items_character_id"), "items", ["character_id"], unique=False)
    op.create_table(
        "oaths",
        sa.Column("character_id", sa.BigInteger(), nullable=False),
        sa.Column("faction", sa.String(length=16), nullable=False),
        sa.Column("sworn_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_oaths_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("character_id", name=op.f("pk_oaths")),
    )
    op.create_table(
        "quest_instances",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("character_id", sa.BigInteger(), nullable=False),
        sa.Column("quest_id", sa.String(length=64), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finishes_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_quest_instances_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quest_instances")),
    )
    op.create_index(
        op.f("ix_quest_instances_character_id"), "quest_instances", ["character_id"], unique=False
    )
    op.create_index(
        op.f("ix_quest_instances_quest_id"), "quest_instances", ["quest_id"], unique=False
    )
    op.create_table(
        "reputation",
        sa.Column("character_id", sa.BigInteger(), nullable=False),
        sa.Column("faction", sa.String(length=16), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_reputation_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("character_id", "faction", name=op.f("pk_reputation")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reputation")
    op.drop_index(op.f("ix_quest_instances_quest_id"), table_name="quest_instances")
    op.drop_index(op.f("ix_quest_instances_character_id"), table_name="quest_instances")
    op.drop_table("quest_instances")
    op.drop_table("oaths")
    op.drop_index(op.f("ix_items_character_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_character_flags_character_id"), table_name="character_flags")
    op.drop_table("character_flags")
    # ### end Alembic commands ###
